name: Run Nimpkgs Crawler

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 2.0.2

      # choosenim cleanup
      - run: rm -r init.sh

      - name: Setup Git Bot
        run: |
          git --version
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Run Crawler
        run: |
          nimble install https://github.com/nimpkgs/crawler -Y
          crawler

      - name: Commit Updates
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "crawler-bot: update nimpkgs"
            git push
          fi
