name: Run Nimpkgs Crawler

on:
  workflow_call:
    inputs:
      flags:
        description: "flags for nimpkgs/crawler"
        type: string
        default: ""

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Git Bot
        run: |
          git --version
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Build Crawler
        run: nix build "github:nimpkgs/crawler"

      - name: Run Crawler
        run: nix run "github:nimpkgs/crawler" -- ${{ inputs.flags }}

      - name: Commit Updates
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "crawler-bot: update nimpkgs"
            git push
          fi
