name: Weekly Crawl

on:
  workflow_dispatch:
  # schedule:
  #   # At 00:00 on Sunday
  #   - cron: '0 0 * * 0'

permissions:
  contents: write

jobs:
  crawl:
    uses: ./.github/workflows/crawl.yml
    with:
      flags: "--check:@valid"
